[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dmdl"
version = "1.1.1"
description = "Dlegoream Media Download Library"
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
dependencies = [
    "yt-dlp>=2024.0.0",
    "Telethon>=1.36.0",
]

authors = [
    {name = "dlegoreamlab"}
]

keywords = [
    "download",
    "media",
    "metadata",
    "dlegoream"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent"
]

[project.urls]
Homepage = "https://github.com/dlegoreamlab/dmdl"

[project.scripts]
dmdl = "dmdl.cli:main"

[tool.setuptools.packages.find]
include = ["dmdl*"]
exclude = ["tests*"]
