from __future__ import annotations

from typing import Any, Protocol


class LoggerProtocol(Protocol):
    def debug(self, message: str, **fields: Any) -> None: ...

    def info(self, message: str, **fields: Any) -> None: ...

    def warning(self, message: str, **fields: Any) -> None: ...

    def error(self, message: str, **fields: Any) -> None: ...

    def exception(self, message: str, **fields: Any) -> None: ...

    def event(self, event_name: str, **fields: Any) -> None: ...
